### ISSUE TITLE
AOT compilation with ng2-bs3-model

### ISSUE THREAD

**Issue by furydam** [dougludlow/ng2-bs3-modal#143]
Hi guys,

I have got this errors during rollup the project.

```Export 'Ng2Bs3ModalModule' is not defined by '/Users/vdzundza/projects/demo-portal-angular/src/main/storefront-spa-webapp/aot/src/app/app.module.ngfactory.js'
Export 'Ng2Bs3ModalModule' is not defined by '/Users/vdzundza/projects/demo-portal-angular/src/main/storefront-spa-webapp/aot/src/app/app.module.ngfactory.js'
'Ng2Bs3ModalModule' is not exported by node_modules/ng2-bs3-modal/ng2-bs3-modal.js (imported by src/app/app.module.js). For help fixing this error see https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
Error: 'Ng2Bs3ModalModule' is not exported by node_modules/ng2-bs3-modal/ng2-bs3-modal.js (imported by src/app/app.module.js). For help fixing this error see https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
```

I've added the ng2-bs3-module to my ngModule import section and also updated the vendor.js file with import statement for a ng2-bs3 modal component.

My app.module.ts is listed below

```
import { NgModule } from '@angular/core';
import { BrowserModule }  from '@angular/platform-browser';
import { FormsModule } from '@angular/forms';
import { HttpModule, JsonpModule } from '@angular/http';
import { RouterModule, Routes } from '@angular/router';
import { Ng2Bs3ModalModule } from 'ng2-bs3-modal/ng2-bs3-modal';

import { AppComponent } from './app.component';
import { PaymentsComponent } from './components/payments/payments.component';
import { InvoicesComponent } from './components/invoices/invoices.component';
import { CustomerListComponent } from './components/customers/customer-list/customer-list.component';
import { CustomerDetailComponent } from './components/customers/customer-detail/customer-detail.component';
import { NavbarMainComponent } from './components/navbar/navbar-main/navbar-main.component';
import { HeaderComponent } from './components/header/header.component';
import { BasketComponent } from './components/basket/basket.component';
import { SsoWidgetComponent } from './components/sso/sso-widget/sso-widget.component';
import { TitleComponent } from './shared/components/title/title.component';
import { ButtonsComponent } from './shared/components/buttons/buttons.component';
import { FormGroupComponent } from './shared/components/form-group/form-group.component';
import { ProductListComponent, ProductListItemComponent } from './components/products/index';


let appRoutes: Routes = [
  { path: '', redirectTo: '/customers', pathMatch: 'full'  },
  { path: 'customers', component: CustomerListComponent },
  { path: 'customer/:id', component: CustomerDetailComponent },
  { path: 'payments', component: PaymentsComponent },
  { path: 'products', component: ProductListComponent },
  { path: 'invoices', component: InvoicesComponent }
];

@NgModule({
  imports: [
    BrowserModule,
    HttpModule,
    JsonpModule,
    FormsModule,
    Ng2Bs3ModalModule,
    RouterModule.forRoot(appRoutes)
  ],
  declarations: [
    AppComponent,
    PaymentsComponent,
    ProductListComponent,
    ProductListItemComponent,
    InvoicesComponent,
    CustomerListComponent,
    CustomerDetailComponent,
    NavbarMainComponent,
    HeaderComponent,
    BasketComponent,
    SsoWidgetComponent,
    TitleComponent,
    ButtonsComponent,
    FormGroupComponent
  ],
  bootstrap: [ AppComponent ]
})
export class AppModule { }
export { appRoutes as routes };

```

Does anyone know how to fix AOT compilation?

**Comment by dougludlow** [comment]
@vdzundza are you using angular-cli? What command are you using to compile your project?

**Comment by lirongfei123** [comment]
me too!
here is my compile option
### tsconfig.json
```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node", 
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [ "es2015", "dom" ],
    "suppressImplicitAnyIndexErrors": true
  },
  "exclude": [
    "node_modules/*",
    "aot/*",
    "app/*-aot.ts"
  ]
}
```
### rollup-config.js
```
import rollup      from 'rollup'
import nodeResolve from 'rollup-plugin-node-resolve'
import commonjs    from 'rollup-plugin-commonjs';
import uglify      from 'rollup-plugin-uglify'

export default {
  entry: 'app/main-aot.js',
  dest: 'dist/build.js', // output a single application bundle
  sourceMap: true,
  sourceMapFile: 'dist/build.js.map',
  format: 'iife',
  plugins: [
    nodeResolve({ jsnext: true, module: true }),
    commonjs({
      include: [
        'node_modules/rxjs/**'
      ],
      namedExports: { 'node_modules/ng2-bs3-modal/ng2-bs3-modal.js': ['Ng2Bs3ModalModule'] }  
    }),
    uglify()
  ]
}
```
### and my build code in the package.json
```
"build": "npm run ngc && npm run rollup",
"ngc": "node_modules/.bin/ngc -p tsconfig-aot.json",
"rollup": "node_modules/.bin/rollup -c rollup-config.js",
```
### the follow is the error
```
⚠️   'Ng2Bs3ModalModule' is not exported by 'node_modules/ng2-bs3-modal/ng2-bs3-modal.js'
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
aot/app/app.module.ngfactory.js (589:31)
587:             return this._CommonModule_0;
588:         }
589:         if ((token === import3.Ng2Bs3ModalModule)) {
                                    ^
590:             return this._Ng2Bs3ModalModule_1;
591:         }

🚨   'Ng2Bs3ModalModule' is not exported by node_modules/ng2-bs3-modal/ng2-bs3-modal.js
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
app/app.module.js (14:9)
12: import { HttpModule } from '@angular/http';
13: import { FormsModule } from '@angular/forms';
14: import { Ng2Bs3ModalModule } from 'ng2-bs3-modal/ng2-bs3-modal';
             ^
15: import { GroupService } from './group/group.service';
16: import { GpDetailService } from './common/gp.detail.service';
```
please help

**Comment by lirongfei123** [comment]
@dougludlow can you  help me

**Comment by Katlianik** [comment]
For me helped this steps:
1. Go to folder node_modules/ng2-bs3-modal
2. Create file tsconfig.json with next content:
```
{
    "compilerOptions": {
        "module": "es2015",
        "moduleResolution": "node",
        "target": "es5",
        "noImplicitAny": false,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "inlineSourceMap": true,
        "declaration": false,
        "rootDir": "./src/ng2-bs3-modal",
        "outDir": ""
    },
    "exclude": [
        "node_modules",
        "demo",
        "bundles",
        "components",
        "directives",
        "src/test",
        "**/*.spec.ts"
    ]
}
```
3. Run tsc

**Comment by wartab** [comment]
I would appreciate if something could be done about this. The quickfix above works, but in larger dev environments issues are bound to occur. Granted, Angular's support for AoT seems like a second thought :)

**Comment by dougludlow** [comment]
@wartab pull requests are welcome 😄. I don't currently have any projects using this and my time has been somewhat limited, but when I get a chance I'll be sure to address this.

**Comment by Rambuto** [comment]
I'm find solution
Need change 
this 
`import { Ng2Bs3ModalModule } from 'ng2-bs3-modal/ng2-bs3-modal';`
to this 
`import { Ng2Bs3ModalModule } from 'ng2-bs3-modal/src/ng2-bs3-modal/ng2-bs3-modal';`

Maybe this can help for some people :+1:

**Comment by wartab** [comment]
I would like to share my findings that I made over the past months and everything described above is not required if you are following Angular's tutorial on using AOT + Rollup.

All you need to do is import the module as described in this doc.
For Rollup, this config works for me using the Rollup common-js plugin.

```
export defaults {
    plugins: [
        commonjs({
            include: [
                "node_modules/ng2-bs3-modal/**",
            ],
            namedExports: [
                "node_modules/ng2-bs3-modal/ng2-bs3-modal.js": ["ModalComponent"],
            ]
        }),
    ],
}
```

**Comment by dougludlow** [comment]
I'm hoping this is fixed with my latest changes on v0.11. I'm using ngc to compile the project.

**Comment by glemiere** [comment]
`/node_modules/ng2-bs3-modal/modal/modal.js:1
(function (exports, require, module, __filename, __dirname) { import { Component, Input, Output, EventEmitter, ElementRef, HostBinding, NgZone } from '@angular/core';
                                                              ^^^^^^`

Not fixed ;-)

**Comment by dougludlow** [comment]
@glemiere try
 
```
import { BsModalComponent } from 'ng2-bs3-modal';
```

instead of  

```
import { BsModalComponent } from 'ng2-bs3-modal/ng2-bs3-modal';
```

It looks like you're trying to import the ESM version.

**Comment by glemiere** [comment]
I did import it the right way, I realised that it is not a problem with your library but with angular itself while using server rendering.
I'm trying to fix it using this workaround : https://github.com/angular/universal-starter/issues/428#issuecomment-331558400

**Comment by sandekuk11** [comment]
use 

**import { BsModalModule } from 'ng2-bs3-modal/ng2-bs3-modal';**

instead of 

**import { Ng2Bs3ModalModule } from 'ng2-bs3-modal/ng2-bs3-modal';**
